export const menuConfigs = {
    guest: [
        { href: "/index.html", text: "Startseite" },
        { href: "/src/pages/verkäufer.html", text: "Verkäufer" },
        { href: "/src/pages/login.html", text: "Anmelden" },
        { href: "/src/pages/register.html", text: "Registrieren" },
        { href: "/src/pages/übertuninghub.html", text: "Über uns" },
        { href: "/src/pages/support.html", text: "Support" },
        { href: "/src/pages/datenschutz.html", text: "Datenschutz" },
        { href: "/src/pages/impressum.html", text: "Impressum" },
    ],
    normal: [
        { href: "/index.html", text: "Startseite" },
        { href: "/src/pages/teilesuchen.html", text: "Teile suchen" },
        { href: "/src/pages/teilehinzufügen.html", text: "Teile verkaufen" },
        { href: "/src/pages/meineteile.html", text: "Meine Anzeigen" },
        { href: "/src/pages/chat.html", text: "Chat" },
        { href: "/src/pages/notifications.html", text: "Benachrichtigungen" },
        { href: "/src/pages/verkäufer.html", text: "Verkäufer" },
        { href: "/src/pages/settings.html", text: "Einstellungen" },
        { href: "/src/pages/support.html", text: "Support" },
        { href: "/src/pages/übertuninghub.html", text: "Über uns" },
        { href: "/src/pages/datenschutz.html", text: "Datenschutz" },
        { href: "/src/pages/impressum.html", text: "Impressum" },
        { href: "#", text: "Abmelden", action: "logout" },
    ],
    business: [
        { href: "/index.html", text: "Startseite" },
        { href: "/src/pages/verkäufer.html", text: "Verkäufer" },
        { href: "/src/pages/settings.html", text: "Einstellungen" },
        { href: "/src/pages/produkteHinzufügen.html", text: "Produkte hinzufügen" },
        { href: "/src/pages/meineProdukte.html", text: "Meine Produkte" },
        { href: "/src/pages/businessShopEinstellungen.html", text: "Shop Einstellungen" },
        { href: "/src/pages/notifications.html", text: "Benachrichtigungen" },
        { href: "/src/pages/support.html", text: "Support" },
        { href: "/src/pages/übertuninghub.html", text: "Über uns" },
        { href: "/src/pages/datenschutz.html", text: "Datenschutz" },
        { href: "/src/pages/impressum.html", text: "Impressum" },
        { href: "#", text: "Abmelden", action: "logout" },
    ],
    admin: [
        { href: "/index.html", text: "Startseite" },
        { href: "/src/pages/admin/tuninghubAdminDashboard.html", text: "Admin Dashboard" },
        { href: "/src/pages/admin/tuninghubAdminNotifications.html", text: "System-Benachrichtigungen" },
        { href: "/src/pages/teilesuchen.html", text: "Teile suchen" },
        { href: "/src/pages/teilehinzufügen.html", text: "Teil hinzufügen" },
        { href: "/src/pages/meineProdukte.html", text: "Meine Produkte" },
        { href: "/src/pages/verkäufer.html", text: "Alle Verkäufer" },
        { href: "/src/pages/settings.html", text: "Einstellungen" },
        { href: "/src/pages/chat.html", text: "Chat" },
        { href: "/src/pages/notifications.html", text: "Benachrichtigungen" },
        { href: "/src/pages/datenschutz.html", text: "Datenschutz" },
        { href: "/src/pages/impressum.html", text: "Impressum" },
        { href: "#", text: "Abmelden", action: "logout" },
    ],
}